CREATE TABLE IF NOT EXISTS categories(
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) DELETE ON CASCADE,
    name VARCHAR(155) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);